Important links:

- https://deeplizard.com/learn/video/Csa5R12jYRg
- https://deeplizard.com/learn/video/AiyK0idr4uM
- https://deeplizard.com/learn/video/k6ZF1TSniYk
- https://deeplizard.com/learn/video/jexkKugTg04

In [ ]:
import numpy as np
import torch #an instance of the Tensor class

dd = [ 
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print(dd) 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Lets look at the axes of our tensor 

In [7]:
#These are the elements in our first axis - they are each arrays
dd[0], dd[1], dd[2]

([1, 2, 3], [4, 5, 6], [7, 8, 9])

Below, for all the indices of the last axis (second)
you will notice that it will just be a number.
The elements for any other axis is always multidimensional arrays

In [8]:
#These are the first index of second axis
dd[0][0], dd[1][0], dd[2][0]

(1, 4, 7)

In [9]:
#These are the second index of second axis
dd[0][1], dd[1][1], dd[2][1]

(2, 5, 8)

In [21]:
#These are the third index of second axis
dd[0][2], dd[1][2], dd[2][2]


(3, 6, 9)

In [11]:
t = torch.Tensor(dd)
shape = t.shape
rank = len(shape) #The rank of a tensor is the length of a tensor's shape/size (the length of that array)

print(shape)
print(rank) # a matrix is a tensor of rank 2 - the number of indices needed to identify each element within the tenso

torch.Size([3, 3])
2


We can also reshape tensors - this keeps the underlying data the same but just changes the original 3x3 shape

In [12]:
reshaped = t.reshape(1,9)
print(reshaped) #reshaped tensor

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [13]:
reshaped.shape
len(reshaped.shape) #rank of the reshaped tensor

#interesting to note that the number of axes (2x2) is the same as the rank (2) for a tensor

2

Example: Now lets see a tensor input to a convolutional neural network (cnn)

a tensor input is usually of rank 4 and it is as follows for images and their peixels

- [B,C, H, W] where B is batch size, color channel, height, and width



Now lets start again with the Tensor class

Tensors in PyTorch arerepresented using the torch.Tensor class

We looked at tensors attributes previously (axis, rank, shape). Now we will look at attributes of PyTorch's implementation of tensors

In [14]:
t = torch.Tensor() # tensors contain data of a uniform type

print(t.dtype) #type of data contained within our tensor. A 32 bit floating point, for examlpe as different on cpu and gpu
print(t.device) #where the tensor data is allocated and where the operation will be perfomred
print(t.layout)


torch.float32
cpu
torch.strided


In [15]:
#pPyTorch supports the use of multiple devices

device = torch.device('cuda:0')
device

device(type='cuda', index=0)

Now lets try out the different data types

In [16]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.,2.,3.])

In [17]:
print(t1.dtype)
print(t2.dtype)

torch.int64
torch.float32


Let's see what happens when we add with two different data types (it gets typecasted to a float)

In [18]:
t1 + t2

tensor([2., 4., 6.])

Now lets see what happens when we add two tensors on different devices

In [19]:
t1 = torch.tensor([1,2,3])
t2 = torch.device('cuda:0')

print(t1.device)
print(t2)

print(t1 + t2) #does not compile

cpu
cuda:0


TypeError: unsupported operand type(s) for +: 'Tensor' and 'torch.device'

Lets look at some examples of creating tensors from data

In [ ]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [ ]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [ ]:
torch.tensor(data)

tensor([1, 2, 3])

In [ ]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [ ]:
torch.from_numpy(data)

tensor([1, 2, 3])

In [ ]:
#identity tensor
print(torch.eye(3))
print(torch.eye(3).shape)
print('The rank of this tensor is', len(torch.eye(3).shape))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.Size([3, 3])
The rank of this tensor is 2


In [ ]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
torch.rand(2,2)

tensor([[0.7561, 0.4538],
        [0.3568, 0.3286]])

Now Let us try using tensorflow

In [5]:
import tensorflow as tf

rank1_tensor = tf.Variable(["Test", "ok", "Dev"], tf.string)
rank2_tensor = tf.Variable([["Test", "ok", "hi"], ["test", "dev", "bye"]])
print(rank2_tensor.dtype)



<dtype: 'string'>


In [ ]:
tf.rank(rank2_tensor)



TensorShape([2, 3])

In [ ]:
rank2_tensor.shape #2 lists and each of those have 3 elemnts in them 

TensorShape([2, 3])

In [11]:
rank = len(rank2_tensor.shape)
print(rank)

2


Now let us look at reshaping of tensors

In [16]:
tensor1 = tf.ones([2,3,1])
print(tensor1)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [19]:
tensor2 = tf.reshape(tensor1, [1,2,3])
print(tensor2)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [22]:
tensor3 = tf.reshape(tensor2, [3,-1]) #-1 tells the tensor to calculate the dimension that it has to be based on the first argument - so it'll be [3,2]
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
